server:
  port: 1234
spring:
  datasource:
    url: jdbc:mysql://172.19.19.19/database?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
  sql:
    init:
      mode: always
      separator: ^;
